### ISSUE TITLE
Error: Directive "@connection" already exists in the schema. It cannot be redefined.

### ISSUE THREAD

**Issue by Albert-Gao** [relay-tools/vscode-apollo-relay#30]
Thanks, this plugin works beautifully.

However, here is my small issue.

## env:

```json
    "react-relay": "0.0.0-experimental-183bdd28",
    "vscode-apollo-relay": "^1.5.0",
    "babel-plugin-relay": "^10.0.1",
    "relay-compiler": "^10.0.1",
    "relay-compiler-language-typescript": "^13.0.1",
    "relay-config": "^10.0.1",
```

## apollo.config.js

```javascript
const { config } = require('vscode-apollo-relay').generateConfig()
module.exports = config
```

## relay.config.js

```javascript
module.exports = {
  // Configuration options accepted by the `relay-compiler` command-line tool and `babel-plugin-relay`.
  src: './app',
  schema: './schema.graphql',
  exclude: ['**/node_modules/**', '**/__mocks__/**', '**/generated/**'],
  language: 'typescript',
}
```

## I have a @ connection directive in my schema

```graphql
"""
Specify a custom store key for this result. See
https://www.apollographql.com/docs/react/advanced/caching/#the-connection-directive
"""
directive @connection(
  """Specify the store key."""
  key: String!

  """
  An array of query argument names to include in the generated custom store key.
  """
  filter: [String!]
) on FIELD
```

Which causes this error
![image](https://user-images.githubusercontent.com/18282328/93541142-b33b0400-f9a9-11ea-8e23-2bd46e36f0da.png)

Any way I can opt-out the config patching for `@ connection`? But when I am using without this plugin, the Apollo VSC plugin will complain about the existence of this connection directive as well.

Kind of confused, anything I am missing here? Thanks in advance.

**Comment by alloy** [comment]
So you have specified this connection directive in your schema yourself? Can you explain why/what it does? (The link in the comment doesn’t seem to work.)

**Comment by Albert-Gao** [comment]
Thanks for the follow up:

I just did a thorough check,

actually, the following GraphQL decalrations,

```graphql
"""
Direct the client to resolve this field locally, either from the cache or local resolvers.
"""
directive @client(
  """
  When true, the client will never use the cache for this value. See
  https://www.apollographql.com/docs/react/essentials/local-state/#forcing-resolvers-with-clientalways-true
  """
  always: Boolean
) on FIELD | FRAGMENT_DEFINITION | INLINE_FRAGMENT

"""
Export this locally resolved field as a variable to be used in the remainder of this query. See
https://www.apollographql.com/docs/react/essentials/local-state/#using-client-fields-as-variables
"""
directive @export(
  """The variable name to export this field as."""
  as: String!
) on FIELD

"""
Specify a custom store key for this result. See
https://www.apollographql.com/docs/react/advanced/caching/#the-connection-directive
"""
directive @connection(
  """Specify the store key."""
  key: String!

  """
  An array of query argument names to include in the generated custom store key.
  """
  filter: [String!]
) on FIELD
```

They are not in the backend generated schema,

they are generated by the Apollo plugin

command: `apollo client:download-schema schema.graphql --config ./apolloSchema.config.js`

```javascript
// apolloSchema.config.js

module.exports = {
  client: {
    service: {
      name: 'TeamingCloudDev',
      url: 'http://localhost:4000/graphql',
      headers: {
        Authorization:'my-fake-jwt',
      },
    },
    includes: ['./app/**/*.tsx'],
    tagName: 'graphql',
  },
}
```

Interesting...Need to find a option for this

**Comment by Albert-Gao** [comment]
It should be controlled by:

```javscript
module.exports = {
  client: {
    clientOnlyDirectives: [],
    clientSchemaDirectives: [],
  },
}
```

according to the [doc](https://www.apollographql.com/docs/devtools/apollo-config/#clientclientonlydirectives-clientclientschemadirectives)

but no matter how I change it, to empty array or false, or null, it keeps generating these directives,

any suggestions? what am i missing here? probably need to start an issue in Apollo repo....

**Comment by alloy** [comment]
Yeah it seems like you wouldn’t want a Apollo Client specific directive such as `@connection`, so probably best to check in with Apollo indeed.
